name: DeepScan Static Analysis

on:
  push:
    branches: [ "**" ]
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
    branches: [ "**" ]

jobs:
  deepscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      - name: Install Dependencies
        run: npm install

      - name: Install DeepScan CLI
        run: npm install -g deepscan

      - name: Run DeepScan
        env:
          DEEPSCAN_TOKEN: ${{ secrets.DEEPSCAN_API_KEY }}
        run: |
          deepscan --project nodebb-f24-d-buggers --analyze .
